# Generated by Django 3.0.7 on 2026-04-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('imports', models.TextField(blank=True, help_text='External imports like css,js files, will be placed in <head> tag (already includes bootstrap4 and jQuery)', null=True)),
                ('content', models.TextField(help_text='Body of the page')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=70, unique=True)),
                ('file', models.FileField(help_text='Please upload static file (image, css, js, etc). This file will be accessible at static/cms/filename', upload_to='static/cms/')),
            ],
        ),
        migrations.CreateModel(
            name='SubNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('nav', models.ForeignKey(on_delete=models.deletion.CASCADE, to='cms.Nav')),
            ],
        ),
    ]
