# Generated by Django 3.0.7 on 2026-04-09 17:55

import cms.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfile',
            name='file',
            field=models.FileField(help_text='Please upload static file (image, css, js, etc). This file will be accessible at static/cms/filename', storage=django.core.files.storage.FileSystemStorage(base_url='/', location='workshop_app'), upload_to=cms.models.get_filename),
        ),
        migrations.AlterField(
            model_name='staticfile',
            name='filename',
            field=models.CharField(max_length=70, unique=True, validators=[cms.models.validate_filename]),
        ),
    ]
